"""sbermap — bidirectional mapper между HA и Sber Smart Home.

Слои:
- **`spec/`** — категории + IMAGE_TYPE_MAP + ha_mapping.
- **`transform/`** — Feature-Descriptor маппер + per-platform helpers.
"""

from __future__ import annotations

from .exceptions import CodecError, MappingError, SbermapError, SpecError
from .spec.ha_mapping import IMAGE_TYPE_MAP, resolve_category, resolve_device_category
from .transform import (
    EQ_PRESET_MANUAL,
    TV_SOURCES,
    ClimateConfig,
    ClimateState,
    CoverConfig,
    CoverStateSnapshot,
    HaEntityData,
    LightConfig,
    StarosSettingEntity,
    VacuumCommand,
    build_button_press_command,
    build_climate_on_off_command,
    build_climate_set_fan_mode_command,
    build_climate_set_hvac_mode_command,
    build_climate_set_temperature_command,
    build_command,
    build_cover_position_command,
    build_cover_stop_command,
    build_fan_preset_command,
    build_fan_turn_off_command,
    build_fan_turn_on_command,
    build_humidifier_on_off_command,
    build_humidifier_set_humidity_command,
    build_humidifier_set_mode_command,
    build_light_command,
    build_number_command,
    build_select_command,
    build_staros_value,
    build_switch_command,
    build_synthetic_equalizer,
    build_tv_channel_command,
    build_tv_custom_key_command,
    build_tv_direction_command,
    build_tv_mute_command,
    build_tv_on_off_command,
    build_tv_source_command,
    build_tv_volume_command,
    build_tv_volume_step_command,
    build_vacuum_command,
    builtin_equalizer_preset_names,
    climate_config_for,
    climate_state_from_dto,
    cover_config_for,
    cover_state_from_dto,
    equalizer_preset_bands,
    light_config_from_dto,
    light_state_from_dto,
    map_device_to_entities,
    map_hvac_mode,
    map_hvac_mode_to_sber,
    map_settings_screen_to_entities,
    product_supports_equalizer,
)

__all__ = [
    "ClimateConfig",
    "ClimateState",
    "CodecError",
    "CoverConfig",
    "CoverStateSnapshot",
    "HaEntityData",
    "EQ_PRESET_MANUAL",
    "IMAGE_TYPE_MAP",
    "LightConfig",
    "MappingError",
    "SbermapError",
    "SpecError",
    "StarosSettingEntity",
    "TV_SOURCES",
    "VacuumCommand",
    "build_command",
    "build_button_press_command",
    "build_climate_on_off_command",
    "build_climate_set_fan_mode_command",
    "build_climate_set_hvac_mode_command",
    "build_climate_set_temperature_command",
    "build_cover_position_command",
    "build_cover_stop_command",
    "build_fan_preset_command",
    "build_fan_turn_off_command",
    "build_fan_turn_on_command",
    "build_humidifier_on_off_command",
    "build_humidifier_set_humidity_command",
    "build_humidifier_set_mode_command",
    "build_light_command",
    "build_number_command",
    "build_select_command",
    "build_staros_value",
    "build_switch_command",
    "build_synthetic_equalizer",
    "builtin_equalizer_preset_names",
    "equalizer_preset_bands",
    "product_supports_equalizer",
    "build_tv_channel_command",
    "build_tv_custom_key_command",
    "build_tv_direction_command",
    "build_tv_mute_command",
    "build_tv_on_off_command",
    "build_tv_source_command",
    "build_tv_volume_command",
    "build_tv_volume_step_command",
    "build_vacuum_command",
    "climate_config_for",
    "climate_state_from_dto",
    "cover_config_for",
    "cover_state_from_dto",
    "light_config_from_dto",
    "light_state_from_dto",
    "map_device_to_entities",
    "map_hvac_mode",
    "map_hvac_mode_to_sber",
    "map_settings_screen_to_entities",
    "resolve_category",
    "resolve_device_category",
]
