"""sbermap — bidirectional mapper между HA и Sber Smart Home.

Standalone-пакет (sibling к `aiosber/`). Single source of truth для всех
конверсий состояний/команд между HA-моделью и Sber-моделью.

Слои:
- **`values/`** — canonical типы (HsvColor, SberValue, SberStateBundle).
- **`spec/`** — категории + IMAGE_TYPE_MAP + ha_mapping.
- **`codecs/`** — wire-encoders (Gateway/C2C).
- **`transform/`** — двусторонние функции:
  - `sber_to_ha()` — общий dispatcher.
  - per-platform helpers (`lights`, `climate_helpers`, `covers`, `fans`,
    `humidifiers`, `vacuums`, `media_players`, `selects`, `numbers`,
    `buttons`, `switches`) — каждый с парой `*_state_from_dto` +
    `build_*_command` для bidirectional поддержки.

Архитектурные правила: гибридный режим — HA enums разрешены **только** в
`transform/` и `spec/ha_mapping.py`; всё остальное standalone (см. CLAUDE.md).
"""

from __future__ import annotations

from .codecs import C2cCodec, Codec, GatewayCodec
from .exceptions import CodecError, MappingError, SbermapError, SpecError
from .spec.ha_mapping import IMAGE_TYPE_MAP, resolve_category
from .transform import (
    TV_SOURCES,
    ClimateConfig,
    ClimateState,
    CoverConfig,
    CoverStateSnapshot,
    HaEntityData,
    LightConfig,
    VacuumCommand,
    apply_reported_state,
    brightness_ha_to_sber,
    build_button_press_command,
    build_climate_on_off_command,
    build_climate_set_fan_mode_command,
    build_climate_set_hvac_mode_command,
    build_climate_set_temperature_command,
    build_cover_position_command,
    build_cover_stop_command,
    build_fan_preset_command,
    build_fan_turn_off_command,
    build_fan_turn_on_command,
    build_humidifier_on_off_command,
    build_humidifier_set_humidity_command,
    build_humidifier_set_mode_command,
    build_light_command,
    build_number_command,
    build_select_command,
    build_switch_command,
    build_tv_channel_command,
    build_tv_custom_key_command,
    build_tv_direction_command,
    build_tv_mute_command,
    build_tv_on_off_command,
    build_tv_source_command,
    build_tv_volume_command,
    build_tv_volume_step_command,
    build_vacuum_command,
    climate_config_for,
    climate_state_from_dto,
    cover_config_for,
    cover_state_from_dto,
    device_dto_to_entities,
    device_dto_to_state_bundle,
    ha_climate_to_sber,
    ha_cover_to_sber,
    ha_light_to_sber,
    ha_switch_to_sber,
    ha_to_sber_generic,
    light_config_from_dto,
    light_state_from_dto,
    map_hvac_mode,
    map_hvac_mode_to_sber,
    map_vacuum_status,
    sber_to_ha,
)
from .values import (
    HsvColor,
    SberState,
    SberStateBundle,
    SberValue,
    ScheduleEvent,
    ScheduleValue,
    ValueType,
    Weekday,
)

__all__ = [
    "C2cCodec",
    "ClimateConfig",
    "ClimateState",
    "Codec",
    "CodecError",
    "CoverConfig",
    "CoverStateSnapshot",
    "GatewayCodec",
    "HaEntityData",
    "HsvColor",
    "IMAGE_TYPE_MAP",
    "LightConfig",
    "MappingError",
    "SberState",
    "SberStateBundle",
    "SberValue",
    "SbermapError",
    "ScheduleEvent",
    "ScheduleValue",
    "SpecError",
    "TV_SOURCES",
    "VacuumCommand",
    "ValueType",
    "Weekday",
    "apply_reported_state",
    "brightness_ha_to_sber",
    "build_button_press_command",
    "build_climate_on_off_command",
    "build_climate_set_fan_mode_command",
    "build_climate_set_hvac_mode_command",
    "build_climate_set_temperature_command",
    "build_cover_position_command",
    "build_cover_stop_command",
    "build_fan_preset_command",
    "build_fan_turn_off_command",
    "build_fan_turn_on_command",
    "build_humidifier_on_off_command",
    "build_humidifier_set_humidity_command",
    "build_humidifier_set_mode_command",
    "build_light_command",
    "build_number_command",
    "build_select_command",
    "build_switch_command",
    "build_tv_channel_command",
    "build_tv_custom_key_command",
    "build_tv_direction_command",
    "build_tv_mute_command",
    "build_tv_on_off_command",
    "build_tv_source_command",
    "build_tv_volume_command",
    "build_tv_volume_step_command",
    "build_vacuum_command",
    "climate_config_for",
    "climate_state_from_dto",
    "cover_config_for",
    "cover_state_from_dto",
    "device_dto_to_entities",
    "device_dto_to_state_bundle",
    "ha_climate_to_sber",
    "ha_cover_to_sber",
    "ha_light_to_sber",
    "ha_switch_to_sber",
    "ha_to_sber_generic",
    "light_config_from_dto",
    "light_state_from_dto",
    "map_hvac_mode",
    "map_hvac_mode_to_sber",
    "map_vacuum_status",
    "resolve_category",
    "sber_to_ha",
]
