"""AUTO-GENERATED. DO NOT EDIT.

Regenerated by `tools/generate_constants.py` from `docs/sber_full_spec.json`.
"""

from __future__ import annotations

from typing import Final

# Все 28 категорий устройств Sber.
ALL_CATEGORIES: Final[frozenset[str]] = frozenset({'curtain', 'gate', 'hub', 'hvac_ac', 'hvac_air_purifier', 'hvac_boiler', 'hvac_fan', 'hvac_heater', 'hvac_humidifier', 'hvac_radiator', 'hvac_underfloor_heating', 'intercom', 'kettle', 'led_strip', 'light', 'relay', 'scenario_button', 'sensor_door', 'sensor_gas', 'sensor_pir', 'sensor_smoke', 'sensor_temp', 'sensor_water_leak', 'socket', 'tv', 'vacuum_cleaner', 'valve', 'window_blind'})

# Features, поддерживаемые HA-интеграцией для категории.
# (subset of all_features — то что реально полезно).
CATEGORY_FEATURES: Final[dict[str, frozenset[str]]] = {
    'curtain': frozenset({'battery_low_power', 'battery_percentage', 'online', 'open_left_percentage', 'open_rate', 'open_right_percentage', 'open_right_set', 'open_right_state', 'open_set', 'open_state', 'signal_strength'}),
    'gate': frozenset({'online', 'open_left_percentage', 'open_left_set', 'open_left_state', 'open_rate', 'open_right_percentage', 'open_right_set', 'open_right_state', 'open_set', 'open_state', 'signal_strength'}),
    'hub': frozenset({'online'}),
    'hvac_ac': frozenset({'hvac_air_flow_direction', 'hvac_air_flow_power', 'hvac_humidity_set', 'hvac_night_mode', 'hvac_temp_set', 'hvac_work_mode', 'on_off', 'online'}),
    'hvac_air_purifier': frozenset({'hvac_air_flow_power', 'hvac_aromatization', 'hvac_ionization', 'hvac_night_mode', 'hvac_replace_filter', 'hvac_replace_ionizator', 'on_off', 'online'}),
    'hvac_boiler': frozenset({'hvac_temp_set', 'hvac_thermostat_mode', 'on_off', 'online', 'temperature'}),
    'hvac_fan': frozenset({'hvac_air_flow_power', 'on_off', 'online'}),
    'hvac_heater': frozenset({'hvac_air_flow_power', 'hvac_temp_set', 'hvac_thermostat_mode', 'on_off', 'online', 'temperature'}),
    'hvac_humidifier': frozenset({'humidity', 'hvac_air_flow_power', 'hvac_humidity_set', 'hvac_ionization', 'hvac_night_mode', 'hvac_replace_filter', 'hvac_replace_ionizator', 'hvac_water_low_level', 'hvac_water_percentage', 'on_off', 'online'}),
    'hvac_radiator': frozenset({'hvac_temp_set', 'on_off', 'online', 'temperature'}),
    'hvac_underfloor_heating': frozenset({'hvac_temp_set', 'hvac_thermostat_mode', 'on_off', 'online', 'temperature'}),
    'intercom': frozenset({'incoming_call', 'online', 'reject_call', 'unlock'}),
    'kettle': frozenset({'child_lock', 'kitchen_water_level', 'kitchen_water_low_level', 'kitchen_water_temperature', 'kitchen_water_temperature_set', 'on_off', 'online'}),
    'led_strip': frozenset({'light_brightness', 'light_colour', 'light_colour_temp', 'light_mode', 'on_off', 'online', 'sleep_timer'}),
    'light': frozenset({'light_brightness', 'light_colour', 'light_colour_temp', 'light_mode', 'on_off', 'online'}),
    'relay': frozenset({'current', 'on_off', 'online', 'power', 'voltage'}),
    'scenario_button': frozenset({'battery_percentag', 'button_1_event', 'button_2_event', 'online', 'signal_strength'}),
    'sensor_door': frozenset({'battery_low_power', 'battery_percentage', 'doorcontact_state', 'online', 'sensor_sensitive', 'signal_strength', 'tamper_alarm'}),
    'sensor_gas': frozenset({'alarm_mute', 'battery_low_power', 'battery_percentage', 'gas_leak_state', 'online', 'sensor_sensitive', 'signal_strength'}),
    'sensor_pir': frozenset({'battery_low_power', 'battery_percentage', 'online', 'pir', 'sensor_sensitive', 'signal_strength'}),
    'sensor_smoke': frozenset({'alarm_mute', 'battery_low_power', 'battery_percentage', 'online', 'signal_strength', 'smoke_state'}),
    'sensor_temp': frozenset({'air_pressure', 'battery_low_power', 'battery_percentage', 'humidity', 'online', 'sensor_sensitive', 'signal_strength', 'temp_unit_view', 'temperature'}),
    'sensor_water_leak': frozenset({'battery_low_power', 'battery_percentage', 'online', 'signal_strength', 'water_leak_state'}),
    'socket': frozenset({'child_lock', 'current', 'on_off', 'online', 'power', 'voltage'}),
    'tv': frozenset({'channel', 'channel_int', 'custom_key', 'direction', 'mute', 'number', 'on_off', 'online', 'source', 'volume', 'volume_int'}),
    'vacuum_cleaner': frozenset({'battery_percentage', 'child_lock', 'online', 'vacuum_cleaner_cleaning_type', 'vacuum_cleaner_command', 'vacuum_cleaner_program', 'vacuum_cleaner_status'}),
    'valve': frozenset({'battery_low_power', 'battery_percentage', 'online', 'open_set', 'open_state', 'signal_strength'}),
    'window_blind': frozenset({'battery_low_power', 'battery_percentage', 'online', 'open_percentage', 'open_rate', 'open_set', 'open_state', 'signal_strength'}),
}

# Обязательные features — должны присутствовать в reported_state любого
# device этой категории. Отсутствие = device считается невалидным.
CATEGORY_OBLIGATORY: Final[dict[str, frozenset[str]]] = {
    'curtain': frozenset({'online', 'open_percentage', 'open_set', 'open_state'}),
    'gate': frozenset({'online', 'open_percentage', 'open_set', 'open_state'}),
    'hub': frozenset({'online'}),
    'hvac_ac': frozenset({'hvac_temp_set', 'on_off', 'online'}),
    'hvac_air_purifier': frozenset({'on_off', 'online'}),
    'hvac_boiler': frozenset({'on_off', 'online'}),
    'hvac_fan': frozenset({'on_off', 'online'}),
    'hvac_heater': frozenset({'on_off', 'online'}),
    'hvac_humidifier': frozenset({'on_off', 'online'}),
    'hvac_radiator': frozenset({'on_off', 'online'}),
    'hvac_underfloor_heating': frozenset({'on_off', 'online'}),
    'intercom': frozenset({'online'}),
    'kettle': frozenset({'on_off', 'online'}),
    'led_strip': frozenset({'on_off', 'online'}),
    'light': frozenset({'on_off', 'online'}),
    'relay': frozenset({'on_off', 'online'}),
    'scenario_button': frozenset({'online'}),
    'sensor_door': frozenset({'doorcontact_state', 'online'}),
    'sensor_gas': frozenset({'gas_leak_state', 'online'}),
    'sensor_pir': frozenset({'online', 'pir'}),
    'sensor_smoke': frozenset({'online', 'smoke_state'}),
    'sensor_temp': frozenset({'humidity', 'online', 'temperature'}),
    'sensor_water_leak': frozenset({'online', 'water_leak_state'}),
    'socket': frozenset({'on_off', 'online'}),
    'tv': frozenset({'on_off', 'online'}),
    'vacuum_cleaner': frozenset({'online'}),
    'valve': frozenset({'online', 'open_percentage', 'open_set', 'open_state'}),
    'window_blind': frozenset({'online', 'open_percentage', 'open_set', 'open_state'}),
}

# Полный список features (включая deprecated/optional) — для discovery.
CATEGORY_ALL_FEATURES: Final[dict[str, frozenset[str]]] = {
    'curtain': frozenset({'battery_low_power', 'battery_percentage', 'online', 'open_left_percentage', 'open_left_set', 'open_left_state', 'open_percentage', 'open_rate', 'open_right_percentage', 'open_right_set', 'open_right_state', 'open_set', 'open_state', 'signal_strength'}),
    'gate': frozenset({'online', 'open_left_percentage', 'open_left_set', 'open_left_state', 'open_percentage', 'open_rate', 'open_right_percentage', 'open_right_set', 'open_right_state', 'open_set', 'open_state', 'signal_strength'}),
    'hub': frozenset({'online'}),
    'hvac_ac': frozenset({'humidity', 'hvac_air_flow_direction', 'hvac_air_flow_power', 'hvac_humidity_set', 'hvac_ionization', 'hvac_night_mode', 'hvac_temp_set', 'hvac_work_mode', 'on_off', 'online', 'temperature'}),
    'hvac_air_purifier': frozenset({'hvac_air_flow_power', 'hvac_aromatization', 'hvac_decontaminate', 'hvac_ionization', 'hvac_night_mode', 'hvac_replace_filter', 'hvac_replace_ionizator', 'on_off', 'online'}),
    'hvac_boiler': frozenset({'hvac_heating_rate', 'hvac_temp_set', 'hvac_thermostat_mode', 'on_off', 'online', 'temperature'}),
    'hvac_fan': frozenset({'hvac_air_flow_power', 'hvac_direction_set', 'on_off', 'online'}),
    'hvac_heater': frozenset({'hvac_air_flow_power', 'hvac_temp_set', 'hvac_thermostat_mode', 'on_off', 'online', 'temperature'}),
    'hvac_humidifier': frozenset({'humidity', 'hvac_air_flow_power', 'hvac_humidity_set', 'hvac_ionization', 'hvac_night_mode', 'hvac_replace_filter', 'hvac_replace_ionizator', 'hvac_water_level', 'hvac_water_low_level', 'hvac_water_percentage', 'on_off', 'online'}),
    'hvac_radiator': frozenset({'hvac_temp_set', 'on_off', 'online', 'temperature'}),
    'hvac_underfloor_heating': frozenset({'hvac_heating_rate', 'hvac_temp_set', 'hvac_thermostat_mode', 'on_off', 'online', 'temperature'}),
    'intercom': frozenset({'incoming_call', 'online', 'reject_call', 'unlock'}),
    'kettle': frozenset({'child_lock', 'kitchen_water_level', 'kitchen_water_low_level', 'kitchen_water_temperature', 'kitchen_water_temperature_set', 'on_off', 'online'}),
    'led_strip': frozenset({'light_brightness', 'light_colour', 'light_colour_temp', 'light_mode', 'on_off', 'online'}),
    'light': frozenset({'light_brightness', 'light_colour', 'light_colour_temp', 'light_mode', 'on_off', 'online'}),
    'relay': frozenset({'current', 'on_off', 'online', 'power', 'voltage'}),
    'scenario_button': frozenset({'battery_low_power', 'battery_percentage', 'button_10_event', 'button_1_event', 'button_2_event', 'button_3_event', 'button_4_event', 'button_5_event', 'button_6_event', 'button_7_event', 'button_8_event', 'button_9_event', 'button_bottom_left_event', 'button_bottom_right_event', 'button_event', 'button_left_event', 'button_right_event', 'button_top_left_event', 'button_top_right_event', 'online', 'signal_strength'}),
    'sensor_door': frozenset({'battery_low_power', 'battery_percentage', 'doorcontact_state', 'online', 'sensor_sensitive', 'signal_strength', 'tamper_alarm'}),
    'sensor_gas': frozenset({'alarm_mute', 'battery_low_power', 'battery_percentage', 'gas_leak_state', 'online', 'sensor_sensitive', 'signal_strength'}),
    'sensor_pir': frozenset({'battery_low_power', 'battery_percentage', 'online', 'pir', 'sensor_sensitive', 'signal_strength'}),
    'sensor_smoke': frozenset({'alarm_mute', 'battery_low_power', 'battery_percentage', 'online', 'signal_strength', 'smoke_state'}),
    'sensor_temp': frozenset({'air_pressure', 'battery_low_power', 'battery_percentage', 'humidity', 'online', 'sensor_sensitive', 'signal_strength', 'temp_unit_view', 'temperature'}),
    'sensor_water_leak': frozenset({'battery_low_power', 'battery_percentage', 'online', 'signal_strength', 'water_leak_state'}),
    'socket': frozenset({'child_lock', 'current', 'on_off', 'online', 'power', 'voltage'}),
    'tv': frozenset({'channel', 'channel_int', 'custom_key', 'direction', 'mute', 'number', 'on_off', 'online', 'source', 'volume', 'volume_int'}),
    'vacuum_cleaner': frozenset({'battery_percentage', 'child_lock', 'online', 'vacuum_cleaner_cleaning_type', 'vacuum_cleaner_command', 'vacuum_cleaner_program', 'vacuum_cleaner_status'}),
    'valve': frozenset({'battery_low_power', 'battery_percentage', 'online', 'open_percentage', 'open_set', 'open_state', 'signal_strength'}),
    'window_blind': frozenset({'battery_low_power', 'battery_percentage', 'light_transmission_percentage', 'online', 'open_percentage', 'open_rate', 'open_set', 'open_state', 'signal_strength'}),
}
