"""AUTO-GENERATED. DO NOT EDIT.

Regenerated by `tools/generate_constants.py` from `docs/sber_full_spec.json`.
"""

from __future__ import annotations

from typing import Final

# Возможные значения для ENUM-фич, объединённые по всем категориям
# (для фичи может быть несколько вариантов в разных категориях — берём union).
FEATURE_ENUMS: Final[dict[str, tuple[str, ...]]] = {
    'button_1_event': ('click', 'double_click',),
    'hvac_air_flow_power': ('auto', 'high', 'low', 'medium', 'turbo',),
    'open_rate': ('auto', 'high', 'low',),
    'sensor_sensitive': ('auto', 'high',),
    'signal_strength': ('high', 'low',),
    'source': ('+', '-', 'av', 'content', 'hdmi1', 'hdmi2', 'hdmi3', 'tv',),
    'vacuum_cleaner_program': ('perimeter', 'smart', 'spot',),
}
