"""AUTO-GENERATED. DO NOT EDIT.

Regenerated by `tools/generate_constants.py` from `docs/sber_full_spec.json`.
"""

from __future__ import annotations

from typing import Final

# Per-category INTEGER ranges {feature: {category: {min, max, step}}}.
# Например `hvac_temp_set` имеет разные диапазоны для radiator (25-40)
# vs boiler (25-80) vs underfloor (25-50).
FEATURE_RANGES: Final[dict[str, dict[str, dict[str, int]]]] = {
    'hvac_temp_set': {
    'hvac_boiler': {'min': 25, 'max': 80, 'step': 5},
    'hvac_radiator': {'min': 25, 'max': 40, 'step': 5},
    'hvac_underfloor_heating': {'min': 25, 'max': 50, 'step': 5},
},
    'kitchen_water_temperature_set': {
    'kettle': {'min': 60, 'max': 100, 'step': 10},
},
    'light_brightness': {
    'led_strip': {'min': 100, 'max': 900, 'step': 1},
    'light': {'min': 100, 'max': 900, 'step': 1},
},
    'power': {
    'relay': {'min': 10, 'max': 45000, 'step': 1},
    'socket': {'min': 10, 'max': 45000, 'step': 1},
},
}
