"""AUTO-GENERATED package — DO NOT EDIT.

Regenerated by `tools/generate_constants.py` (target=sbermap).
Source: docs/sber_full_spec.json (snapshot реверс-инжиниринга APK).
"""

from __future__ import annotations

from .categories import (
    ALL_CATEGORIES,
    CATEGORY_ALL_FEATURES,
    CATEGORY_FEATURES,
    CATEGORY_OBLIGATORY,
)
from .feature_enums import FEATURE_ENUMS
from .feature_ranges import FEATURE_RANGES
from .feature_types import FEATURE_TYPES

__all__ = [
    "ALL_CATEGORIES",
    "CATEGORY_ALL_FEATURES",
    "CATEGORY_FEATURES",
    "CATEGORY_OBLIGATORY",
    "FEATURE_ENUMS",
    "FEATURE_RANGES",
    "FEATURE_TYPES",
]
