#!/usr/bin/env python3
"""Auto-generate constants from `docs/sber_full_spec.json`.

Регенерирует `aiosber/_generated/*.py` файлы:
- `category_features.py` — CATEGORY_FEATURES, CATEGORY_OBLIGATORY, CATEGORY_ALL_FEATURES.
- `feature_types.py` — FEATURE_TYPES (BOOL/INTEGER/FLOAT/ENUM/...) для каждой feature.
- `feature_enums.py` — FEATURE_ENUMS (доступные значения для ENUM-фич).
- `feature_ranges.py` — FEATURE_RANGES (min/max/step для INTEGER-фич).

Запуск:

    python tools/generate_constants.py

Один источник истины — `docs/sber_full_spec.json`. При изменении spec
(или обновлении из новой версии APK) — перезапустить script.

Автоматически: мы НЕ обновляем сгенерированные файлы вручную.
"""

from __future__ import annotations

import json
import sys
from collections import defaultdict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SPEC_PATH = REPO_ROOT / "docs" / "sber_full_spec.json"
OUTPUT_DIR = REPO_ROOT / "custom_components" / "sberhome" / "aiosber" / "_generated"


HEADER = '''"""AUTO-GENERATED. DO NOT EDIT.

Regenerated by `tools/generate_constants.py` from `docs/sber_full_spec.json`.
"""

from __future__ import annotations

from typing import Final

'''


def _format_strset(values) -> str:
    """`frozenset({"a", "b"})` literal."""
    items = ", ".join(repr(v) for v in sorted(values))
    return f"frozenset({{{items}}})" if values else "frozenset()"


def _format_dict(d: dict, value_fmt) -> str:
    """{key: value} pretty-printed dict literal."""
    if not d:
        return "{}"
    lines = ["{"]
    for k in sorted(d):
        v = value_fmt(d[k])
        lines.append(f"    {k!r}: {v},")
    lines.append("}")
    return "\n".join(lines)


def gen_category_features(spec: dict) -> str:
    cats = spec["categories"]
    cat_features = {c: cats[c].get("features", []) for c in cats}
    cat_obligatory = {c: cats[c].get("obligatory", []) for c in cats}
    cat_all = {c: cats[c].get("all_features", []) for c in cats}
    out = HEADER
    out += "# Все 28 категорий устройств Sber.\n"
    out += "ALL_CATEGORIES: Final[frozenset[str]] = " + _format_strset(cats.keys()) + "\n\n"

    out += "# Features, поддерживаемые HA-интеграцией для категории.\n"
    out += "# (subset of all_features — то что реально полезно).\n"
    out += "CATEGORY_FEATURES: Final[dict[str, frozenset[str]]] = "
    out += _format_dict(cat_features, _format_strset) + "\n\n"

    out += "# Обязательные features — должны присутствовать в reported_state любого\n"
    out += "# device этой категории. Отсутствие = device считается невалидным.\n"
    out += "CATEGORY_OBLIGATORY: Final[dict[str, frozenset[str]]] = "
    out += _format_dict(cat_obligatory, _format_strset) + "\n\n"

    out += "# Полный список features (включая deprecated/optional) — для discovery.\n"
    out += "CATEGORY_ALL_FEATURES: Final[dict[str, frozenset[str]]] = "
    out += _format_dict(cat_all, _format_strset) + "\n"
    return out


def gen_feature_types(spec: dict) -> str:
    """Для каждой feature собрать её type (BOOL/INTEGER/FLOAT/ENUM/STRING).

    Тип берётся из allowed_values если есть, иначе эвристика по имени:
    *_state/on_off/_mute/_lock/_alarm — BOOL,
    temperature/humidity/pressure — FLOAT,
    *_int/_percentage/_set/_voltage/_current/_power/timer/level — INTEGER,
    *_event/_mode/_status — ENUM.
    """
    cats = spec["categories"]
    feature_types: dict[str, str] = {}
    for cat in cats.values():
        allowed = cat.get("allowed_values", {})
        for f in cat.get("all_features", []):
            if f in feature_types:
                continue
            if f in allowed:
                feature_types[f] = allowed[f].get("type", "STRING")
            else:
                feature_types[f] = _guess_type(f)
    out = HEADER
    out += "# Wire-тип каждой feature: BOOL/INTEGER/FLOAT/ENUM/STRING/COLOR/SCHEDULE.\n"
    out += "# Источник: allowed_values из spec, fallback — эвристика по имени.\n"
    out += "FEATURE_TYPES: Final[dict[str, str]] = "
    out += _format_dict(feature_types, repr) + "\n"
    return out


def _guess_type(feature: str) -> str:
    """Эвристика: тип wire-значения по имени feature."""
    f = feature.lower()
    bool_markers = (
        "_state",
        "_lock",
        "_alarm",
        "_mute",
        "online",
        "on_off",
        "_low_power",
        "_low_level",
        "incoming_call",
        "reject_call",
        "unlock",
        "night_mode",
        "ionization",
        "aromatization",
        "decontaminate",
        "_filter",
        "_ionizator",
        "tamper",
    )
    int_markers = (
        "_int",
        "_percentage",
        "_set",
        "voltage",
        "current",
        "power",
        "timer",
        "_level",
    )
    enum_markers = (
        "_mode",
        "_event",
        "_status",
        "_rate",
        "source",
        "direction",
        "channel",
        "volume",
        "custom_key",
    )
    float_markers = ("temperature", "humidity", "pressure")

    if "_set" in f or "_percentage" in f:
        return "INTEGER"
    if any(m in f for m in bool_markers):
        return "BOOL"
    if any(m in f for m in float_markers):
        return "FLOAT"
    if any(m in f for m in enum_markers):
        return "ENUM"
    if any(m in f for m in int_markers):
        return "INTEGER"
    return "STRING"


def gen_feature_enums(spec: dict) -> str:
    """Собрать enum_values для всех ENUM-фич всех категорий."""
    cats = spec["categories"]
    feature_enums: dict[str, list[str]] = {}
    for cat in cats.values():
        for f, av in cat.get("allowed_values", {}).items():
            if av.get("type") == "ENUM":
                values = av.get("enum_values", {}).get("values", [])
                if f in feature_enums:
                    # union — некоторые фичи могут иметь разные enum в разных категориях
                    feature_enums[f] = sorted(set(feature_enums[f]) | set(values))
                else:
                    feature_enums[f] = list(values)
    out = HEADER
    out += "# Возможные значения для ENUM-фич, объединённые по всем категориям\n"
    out += "# (для фичи может быть несколько вариантов в разных категориях — берём union).\n"
    out += "FEATURE_ENUMS: Final[dict[str, tuple[str, ...]]] = "
    out += _format_dict(feature_enums, lambda v: "(" + ", ".join(repr(x) for x in sorted(v)) + ",)") + "\n"
    return out


def gen_feature_ranges(spec: dict) -> str:
    """Range (min/max/step) для INTEGER-фич."""
    cats = spec["categories"]
    feature_ranges: dict[str, dict[str, dict[str, int]]] = defaultdict(dict)
    for cat_name, cat in cats.items():
        for f, av in cat.get("allowed_values", {}).items():
            if av.get("type") == "INTEGER":
                iv = av.get("integer_values", {})
                if not iv:
                    continue
                # Per-category ranges (бывают разные диапазоны для одной фичи)
                feature_ranges[f][cat_name] = {
                    "min": int(iv.get("min", 0)),
                    "max": int(iv.get("max", 0)),
                    "step": int(iv.get("step", 1)),
                }
    out = HEADER
    out += "# Per-category INTEGER ranges {feature: {category: {min, max, step}}}.\n"
    out += "# Например `hvac_temp_set` имеет разные диапазоны для radiator (25-40)\n"
    out += "# vs boiler (25-80) vs underfloor (25-50).\n"
    out += "FEATURE_RANGES: Final[dict[str, dict[str, dict[str, int]]]] = "
    out += _format_dict(
        dict(feature_ranges),
        lambda v: _format_dict(v, lambda r: repr(r)),
    ) + "\n"
    return out


def main() -> int:
    if not SPEC_PATH.exists():
        print(f"ERROR: spec not found at {SPEC_PATH}", file=sys.stderr)
        return 1

    spec = json.loads(SPEC_PATH.read_text(encoding="utf-8"))
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    files = {
        "__init__.py": '"""AUTO-GENERATED package — DO NOT EDIT.\n\nRegenerated by `tools/generate_constants.py`.\n"""\n',
        "category_features.py": gen_category_features(spec),
        "feature_types.py": gen_feature_types(spec),
        "feature_enums.py": gen_feature_enums(spec),
        "feature_ranges.py": gen_feature_ranges(spec),
    }

    for name, content in files.items():
        path = OUTPUT_DIR / name
        path.write_text(content, encoding="utf-8")
        print(f"  wrote {path.relative_to(REPO_ROOT)} ({len(content)} chars)")

    print(f"\n✅ Regenerated {len(files)} files in {OUTPUT_DIR.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
